apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ app_name }}-cluster-role
rules:
  - apiGroups:
    - ""
    resources:
      - configmaps
    verbs:
      - get
      - watch
      - list
  - apiGroups:
    - ""
    resources:
      - secrets
    verbs:
      - get
      - create
  - apiGroups:
    - ""
    resources:
      - pods
      - pods/exec
      - pods/log
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups:
    - ""
    resources:
      - events
    verbs:
      - watch
      - create
      - patch
  - apiGroups:
    - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
  - apiGroups: 
    - argoproj.io
    resources:
      - eventsources
      - sensors
      - workflows
      - workfloweventbindings
      - workflowtemplates
      - cronworkflows
      - clusterworkflowtemplates
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ app_name }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ app_name }}-cluster-role
subjects:
- kind: ServiceAccount
  name: {{ app_name }}
  namespace: {{ namespace }}